name: workflow

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup of JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
      - name: run test
        run: mvn test
      - name: mvn install
        run: mvn clean install -DskipTests